[package]
name = "lizard"
version = "0.4.0"
edition = "2021"

[dependencies]
confy = "0.5.0"
gtk = "0.15.5"
image = "0.24.4"
libappindicator = "0.7.1"
notify-rust = "4.5.10"
rust-embed="6.4.1"
serde = { version = "1.0.130", features = ["derive"] }
serde_derive = "1.0.145"